# fly.toml app configuration file generated for pizzahut on 2024-02-28T10:57:12+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pizzahut'
primary_region = 'lax'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  max_machines_running = 1
  min_machines_running = 1
  [http_service.concurrency]
    type = "requests"
    soft_limit = 300
    hard_limit = 500
  processes = ['app']

[[vm]]
  size = "shared-cpu-4x"
  memory = "2gb"
